name: Docker Image CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux/amd64
            tag: amd64
          - platform: linux/arm64
            tag: arm64
          - platform: linux/arm/v6
            tag: arm-v6
          - platform: linux/arm/v7
            tag: arm-v7
          - platform: linux/s390x
            tag: s390x
          - platform: linux/ppc64le
            tag: ppc64le

    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build Docker image for ${{ matrix.platform }}
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        platforms: ${{ matrix.platform }}
        push: false
        load: true
        tags: altair-mpm:${{ matrix.tag }}
